// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

import config from './docusaurus.config';

const providerTitle = config.title.replace(/^StackQL /, '').replace(/ Provider$/, '');

 const sidebars = {
  mainSidebar: [
    // Way back to the main stackql.io docs, as on the query library site.
    // '/stackqldocs' is this site's redirect page (src/pages/stackqldocs.js).
    // The arrow and divider come from the .sidebar-back-link rules in the
    // site stylesheet.
    {
      type: 'link',
      label: 'Back to StackQL Docs',
      href: '/stackqldocs',
      className: 'sidebar-back-link',
    },
    {
      type: 'link',
      label: 'All Providers',
      href: '/providers',
    },
    {
      type: 'category',
      label: `${providerTitle} Provider`,
      link: {type: 'doc', id: 'provider-intro'},
      items: [
        {
          type: 'autogenerated', 
          dirName: 'services',
        }
      ]
    },    
  ],
};

export default sidebars;
